import type { Reservation, ReservationStatus } from '../../types/reservations';
import { formatCurrency, formatDate } from '../../utils/helpers';
import ActionButtons from './ActionButtons';

type ReservationCardProps = { reservation: Reservation; onUpdate: (id: string, status: ReservationStatus) => void; onRequestReason: (reservation: Reservation, status: 'Rejected' | 'Cancelled') => void };
const statusClasses: Record<ReservationStatus, string> = { Pending: 'bg-amber-100 text-amber-800', Confirmed: 'bg-blue-100 text-blue-800', Completed: 'bg-emerald-100 text-emerald-800', Cancelled: 'bg-gray-200 text-gray-700', Rejected: 'bg-red-100 text-red-800' };
const Detail = ({ label, value }: { label: string; value: string | number | undefined }) => value === undefined ? null : <div><dt className="text-xs font-medium uppercase tracking-wide text-gray-400">{label}</dt><dd className="mt-1 text-sm font-medium text-gray-700">{value}</dd></div>;

const CategoryDetails = ({ reservation }: { reservation: Reservation }) => {
  if (['Hotel', 'Motel', 'Apartment'].includes(reservation.category)) return <><Detail label="Check-in" value={reservation.checkIn && formatDate(reservation.checkIn)} /><Detail label="Check-out" value={reservation.checkOut && formatDate(reservation.checkOut)} /><Detail label="Guests" value={reservation.guests} /><Detail label="Room type" value={reservation.roomType} /></>;
  if (reservation.category === 'Car Rental') return <><Detail label="Pickup date" value={reservation.pickupDate && formatDate(reservation.pickupDate)} /><Detail label="Return date" value={reservation.returnDate && formatDate(reservation.returnDate)} /><Detail label="Vehicle type" value={reservation.vehicleType} /></>;
  if (reservation.category === 'Tour Agency') return <><Detail label="Tour date" value={reservation.tourDate && formatDate(reservation.tourDate)} /><Detail label="Tour package" value={reservation.tourPackage} /><Detail label="Group size" value={reservation.groupSize} /></>;
  if (reservation.category === 'Tour Guide') return <><Detail label="Tour date" value={reservation.tourDate && formatDate(reservation.tourDate)} /><Detail label="Group size" value={reservation.groupSize} /></>;
  if (reservation.category === 'Attraction') return <><Detail label="Visit date" value={reservation.visitDate && formatDate(reservation.visitDate)} /><Detail label="Visitors" value={reservation.visitors} /></>;
  return <><Detail label="Reservation date" value={formatDate(reservation.reservationDate)} /><Detail label="Party size" value={reservation.partySize} /></>;
};

const ReservationCard = ({ reservation, onUpdate, onRequestReason }: ReservationCardProps) => <article className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">{reservation.confirmationCode}</p><h3 className="mt-1 text-lg font-bold text-gray-900">{reservation.guestName}</h3><p className="mt-1 text-sm text-gray-500">{reservation.guestEmail} · {reservation.guestPhone}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClasses[reservation.status]}`}>{reservation.status}</span></div><dl className="mt-5 grid grid-cols-2 gap-x-5 gap-y-4 border-y border-gray-100 py-4 sm:grid-cols-4"><Detail label="Reservation date" value={formatDate(reservation.reservationDate)} /><Detail label="Total price" value={formatCurrency(reservation.totalPrice, reservation.currency)} /><Detail label="Currency" value={reservation.currency} /><CategoryDetails reservation={reservation} /></dl><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-wide text-gray-400">Special requests</p><p className="mt-1 text-sm text-gray-600">{reservation.specialRequests || 'No special requests.'}</p>{reservation.actionReason && <p className="mt-2 text-xs text-gray-500">Provider note: {reservation.actionReason}</p>}</div><ActionButtons reservation={reservation} onUpdate={onUpdate} onRequestReason={onRequestReason} /></div></article>;

export default ReservationCard;
